---
title: "Final Project"
author: "Jie Li"
date: "11/24/2021"
output:
  html_document: 
    toc: yes
    toc_float: yes
    code_folding: hide
    theme: paper
  pdf_document: default
---

<style>
p.caption {
  font-size: 0.8em;
  text-align: center;
  font-weight: normal;
}
    caption {
      color: grey;
      font-size: 0.8em;
    } 
body{
  font-size: 11pt;
  font-family: Open Sans;
}
h1,h2,h3,h4,h5,h6{
  font-family: Open Sans;
}
td{
  font-size: 9pt;
  font-family: Open Sans;
}
th{
  font-size: 0.8em;
  font-family: Open Sans;
  color: grey;
}
</style>
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r set_up}
crs = 'EPSG:26913'

library(stringr)
library(tidyverse)
library(sf)
library(lubridate)
library(tigris)
library(gganimate)
library(riem)
library(gridExtra)
library(knitr)
library(kableExtra)
library(FNN)
library(spdep)
library(caret)
library(ckanr)
library(grid)
library(gridExtra)
library(knitr)
library(kableExtra)
library(tidycensus)
library(scales)
library(stargazer)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(mapview)
library(ggmap)
library(jsonlite)

ll <- function(dat, proj4 = 4326){
st_transform(dat, proj4)
}

root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

windowsFonts(font = windowsFont('Helvatica'))
plotTheme <- function(base_size = 9, title_size = 10){
  theme(
    text = element_text(family = 'font', color = "black"),
    plot.title = element_text(family = 'font',
                              size = title_size, colour = "black", hjust = 0.5), 
    plot.subtitle = element_text(family = 'font', face = 'italic',
                                 size = base_size, colour = "black", hjust = 0.5),
    plot.caption = element_text(family = 'font', hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_line("grey80", size = 0.01),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=.5),
    strip.background = element_blank(),
    strip.text = element_text(family = 'font', size=9),
    axis.title = element_text(family = 'font', size=9),
    axis.text = element_text(family = 'font', size=7),
    axis.text.y = element_text(family = 'font', size=7),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(family = 'font', colour = "black", face = "italic", size = 9),
    legend.text = element_text(family = 'font', colour = "black", face = "italic", size = 7),
    strip.text.x = element_text(family = 'font', size = 9),
    legend.key.size = unit(.5, 'line')
  )
}

mapTheme <- function(base_size = 9, title_size = 10){
  theme(
    text = element_text(family = 'font', color = "black"),
    plot.title = element_text(family = 'font',
                              size = title_size, colour = "black", hjust = 0.5), 
    plot.subtitle = element_text(family = 'font', face = 'italic',
                                 size = base_size, colour = "black", hjust = 0.5),
    plot.caption = element_text(family = 'font', hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=.5),
    strip.background = element_blank(),
    strip.text = element_text(family = 'font', size=9),
    axis.title = element_text(family = 'font', size=9),
    axis.text = element_text(family = 'font', size=7),
    axis.text.y = element_text(family = 'font', size=7),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(family = 'font', colour = "black", face = "italic", size = 9),
    legend.text = element_text(family = 'font', colour = "black", face = "italic", size = 7),
    strip.text.x = element_text(family = 'font', size = 9),
    legend.key.size = unit(.5, 'line')
  )
}

brightRed = '#f2727f'
lightRed = '#F9B294'
darkBlue = '#315d7f'
palette5 <- c("#f9b294","#f2727f","#c06c86","#6d5c7e","#315d7f")
palette4 <- c("#f9b294","#f2727f","#c06c86","#6d5c7e")
palette2 <- c("#f9b294","#f2727f")
palette1_main <- "#F2727F"
palette1_assist <- '#F9B294'
```

```{r geographies}
njCounties =
  tigris::counties(state = "34")%>%
  st_transform(crs)%>%
  dplyr::select(GEOID,NAMELSAD,geometry)
nyCounties = 
  tigris::counties(state = "NY")%>%
  st_transform(crs)%>%
  dplyr::select(GEOID,NAMELSAD,geometry)
paCounties = 
  tigris::counties(state = "PA")%>%
  st_transform(crs)%>%
  dplyr::select(GEOID,NAMELSAD,geometry)

counties = rbind(njCounties, nyCounties, paCounties)
# 
# njTracts <- 
#   tigris::tracts(state = "34") %>%
#   st_transform(crs)%>%
#   dplyr::select(GEOID,NAMELSAD,geometry)

mapview(counties) + mapview(njStations)
trains %>%
  filter(stop_sequence == 1) %>%
  dplyr::select(to) %>%
  unique() %>%
  mapview()
# grid.arrange(ncol=2,
# ggplot(njCensusCounties)+geom_sf(),
# ggplot(njCensusTracts)+geom_sf())
```

```{r nj_stations}

njStations = st_read('https://opendata.arcgis.com/datasets/4809dada94c542e0beff00600ee930f6_0.geojson') %>%
  st_transform(crs) %>%
  dplyr::select(station = STATION_ID, geometry) %>%
  # Trying to standardize the station names...
  mutate(station = tolower(station)) %>%
  mutate(station = 
           case_when(
             # str_detect(station, '-') ~
             #   substr(station, 1, str_locate(station, '-')[[1]] - 1),
             substr(station, nchar(station) - 15, nchar(station)) == ' railway station'~
               substr(station, 1, nchar(station) - 16),
             substr(station, nchar(station) - 12, nchar(station)) == ' rail station'~
               substr(station, 1, nchar(station) - 13),
             substr(station, nchar(station) - 7, nchar(station)) == ' station' ~
               substr(station, 1, nchar(station) - 8),
             substr(station, nchar(station) - 8, nchar(station)) == ' terminal' ~
               substr(station, 1, nchar(station) - 9),
             TRUE ~ station
           )) %>%
  mutate(joined = 1)

# Further modifying station names
njStations[12, 1] = 'middletown nj'
njStations[149, 1] = 'middletown ny'
njStations[131, 1] = 'anderson street'
njStations[99, 1] = 'atlantic city rail'
njStations[87, 1] = 'bay street'
njStations[134, 1] = 'wood ridge'
njStations[90, 1] = 'watsessing avenue'
njStations[133, 1] = 'teterboro'
njStations[159, 1] = 'secaucus upper lvl'
njStations[166, 1] = 'secaucus lower lvl'
njStations[102, 1] = 'ramsey main st'
njStations[156, 1] = 'ramsey route 17'
njStations[102, 1] = 'ramsey main st'
njStations[115, 1] = 'radburn fair lawn'
njStations[140, 1] = 'princeton junction'
njStations[92, 1] = 'philadelphia'
njStations[165, 1] = 'pennsauken'
njStations[80, 1] = 'mountain view'
njStations[163, 1] = 'mount arlington'
njStations[158, 1] = 'montclair state u'
njStations[107, 1] = 'glen rock main line'
njStations[114, 1] = 'glen rock boro hall'
njStations[116, 1] = 'broadway fair lawn'
njStations[132, 1] = 'essex street'

njStations = njStations %>%
  st_join(counties %>% dplyr::select(GEOID, geometry),
          join = st_within)
```

```{r,fig.height = 3}
base_map <- get_map(location = unname(st_bbox(ll(st_buffer(st_union(njCounties),11000)))),maptype = "terrian")

ggmap(base_map) + 
  geom_sf(data=ll(st_union(njCounties)),color="black",size=1.5,fill = "transparent",inherit.aes = FALSE)+
  geom_sf(data=ll(njCounties),color="black",size=0.5,linetype ="dashed",fill = "transparent",inherit.aes = FALSE)+
  geom_sf(data=ll(njStations),size=1.75,color=palette1_main,inherit.aes = FALSE)+
  labs(title = "Map of NJ Transit Railway Stations", 
       subtitle = "Red dots are stations")+
  mapTheme()

```

```{r read_trains_data}
trainsSep = read.csv('2019_09.csv') %>%
  filter(., type == 'NJ Transit' & status == 'departed' &
           line != 'Princeton Shuttle') %>%
  mutate(date = ymd(date),
         scheduled_time = ymd_hms(scheduled_time),
         actual_time = ymd_hms(actual_time)) %>%
  dplyr::select(-status,-type)

trainsOct = read.csv('2019_10.csv') %>%
  filter(., type == 'NJ Transit' & status == 'departed' &
           line != 'Princeton Shuttle') %>%
  mutate(date = ymd(date),
         scheduled_time = ymd_hms(scheduled_time),
         actual_time = ymd_hms(actual_time)) %>%
  arrange(stop_sequence) %>%
  dplyr::select(-status,-type)

# Bind the two-month data
trains = rbind(trainsSep, trainsOct) %>%
  # Trying to standardize station names
  mutate(to = tolower(to),
         from = tolower(from)) 


trainsWithGeometry = trains %>%
  filter(., to != 'secaucus concourse') %>%
  mutate(to = 
           case_when(
             str_detect(to, '-') ~
               substr(to, 1, str_locate(to, '-')[[1]] - 1),
             substr(to, nchar(to) - 15, nchar(to)) == ' railway station'~
               substr(to, 1, nchar(to) - 16),
             substr(to, nchar(to) - 12, nchar(to)) == ' rail station'~
               substr(to, 1, nchar(to) - 13),
             substr(to, nchar(to) - 7, nchar(to)) == ' station' ~
               substr(to, 1, nchar(to) - 8),
             substr(to, nchar(to) - 8, nchar(to)) == ' terminal' ~
               substr(to, 1, nchar(to) - 9),
             TRUE ~ to
           ),
         from = 
           case_when(
             str_detect(from, '-') ~
               substr(from, 1, str_locate(from, '-')[[1]] - 1),
             substr(from, nchar(from) - 15, nchar(from)) == ' railway station'~
               substr(from, 1, nchar(from) - 16),
             substr(from, nchar(from) - 12, nchar(from)) == ' rail station'~
               substr(from, 1, nchar(from) - 13),
             substr(from, nchar(from) - 7, nchar(from)) == ' station' ~
               substr(from, 1, nchar(from) - 8),
             substr(from, nchar(from) - 8, nchar(from)) == ' terminal' ~
               substr(from, 1, nchar(from) - 9),TRUE ~ from
           )) %>%
  left_join(njStations, by = c('to' = 'station')) %>%
  st_sf() %>%
  dplyr::select(-joined)
```

```{r,fig.width = 3}
#不同线路的平均延迟时间
trainsWithGeometry%>%
  st_drop_geometry()%>%
  dplyr::select(delay_minutes,line)%>%
  na.omit()%>%
  group_by(line)%>%
  summarise(averageDelay=mean(delay_minutes))%>%
  ggplot(aes(line,averageDelay))+
  geom_bar(fill=palette1_main,position ="dodge", stat ="summary", fun ="mean")+
  plotTheme()+ 
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r,fig.height =6}
#同一线路的不同站的平均时间（13条线）
trainsWithGeometry%>%
  st_drop_geometry()%>%
  dplyr::select(to,delay_minutes,line)%>%
  na.omit()%>%
  group_by(to,line)%>%
  summarise(averageDelay=mean(delay_minutes))%>%
  ggplot(aes(to,averageDelay))+
  geom_bar(fill=palette1_main,position ="dodge", stat ="summary", fun ="mean")+
  facet_wrap(~line, scales = "free",ncol=3)+
  labs(title = "Average delay for every station in every line")+
  plotTheme()+ 
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust = 1),
        panel.spacing = unit(2, 'lines'))
```

```{r,fig.height =2,fig.width=6}
#No Jersey Coast(最多28个站)的不同时间段的线的平均延迟时间as the fucntion of hour
#secodn graph （single station,1条线）

### 两个时间段的星期数对不上？？？
monday <-trainsWithGeometry%>%
  st_drop_geometry()%>%
  filter(line=="No Jersey Coast")%>%
  na.omit()%>%
  mutate(interval_hour = ymd_h(substr(scheduled_time, 1, 13)),
         dayotw = wday(interval_hour),
         week = week(scheduled_time),
         hour = hour(scheduled_time))%>%
  arrange(dayotw,interval_hour)%>%
  filter(week%in%(36:43))%>%
  mutate(monday = ifelse(dayotw == 1 & hour == 0,interval_hour, 0)) %>%
  filter(monday != 0)

grid.arrange(ncol=1,
a=trainsWithGeometry%>%
  st_drop_geometry()%>%
  filter(line=="No Jersey Coast")%>%
  na.omit()%>%
  mutate(interval_hour = ymd_h(substr(scheduled_time, 1, 13)),
         week = week(scheduled_time))%>%
  filter(week%in%(36:43))%>%
  group_by(interval_hour,line,date)%>%
  summarise(AverageDelayInHour = mean(delay_minutes))%>%
  ggplot(aes(interval_hour,AverageDelayInHour)) + 
  geom_line(color=palette1_main,size=0.5)+
  geom_vline(data = monday, aes(xintercept = interval_hour),linetype = "dashed",size=1)+
  labs(title = "No Jersey Coast")+
  plotTheme(),
trainsWithGeometry%>%
  st_drop_geometry()%>%
  filter(line=="No Jersey Coast" & to=="hazlet")%>%
  na.omit()%>%
  mutate(interval_hour = ymd_h(substr(scheduled_time, 1, 13)),
         week = week(scheduled_time))%>%
  filter(week%in%(36:43))%>%
  group_by(interval_hour,date)%>%
  summarise(AverageDelayInHour = mean(delay_minutes))%>%
  ggplot(aes(interval_hour,AverageDelayInHour)) + 
  geom_line(color=palette1_main,size=0.5)+
  geom_vline(data = monday, aes(xintercept = interval_hour),linetype = "dashed",size=1)+
  labs(title = "hazlet station")+
  plotTheme())
```

```{r illustrate trainID and express line, eval=FALSE}
## A trainID for a whole trip
trainIDforWholeTrip = trains%>%
  filter(train_id == 7824, date == "2019-10-06")%>%
  arrange(date, train_id)%>%
  dplyr::select(date,train_id,stop_sequence,from,to,line)

kable(trainIDforWholeTrip,align = 'c',caption = '<center>Table.A trainID for a whole trip</center>')%>%
  kable_classic(full_width = T)%>%
  kable_styling(position = "center",font_size = 12)%>%
  column_spec(2, background = palette1_assist)%>%
  column_spec(3, background = palette1_main)

## Different TrainIDs within the same day & Express or normal lines
difTrainIDs = trains%>%
  filter(line=="Northeast Corrdr",date=="2019-10-06",stop_sequence=="2")%>%
  arrange(date,train_id)%>%
  dplyr::select(scheduled_time,train_id,from,to,line)
difTrainIDs = difTrainIDs[1:5,]

kable(difTrainIDs,align = 'c',caption = '<center>Table.Different TrainIDs within the same day & Express or normal lines')%>%
  kable_classic(full_width = T)%>%
  kable_styling(position = "center",font_size = 12)%>%
  column_spec(2, background = palette1_assist)%>%
  row_spec(2, background = palette1_main)%>%
  row_spec(3, background = palette1_main)

## A TrainID is allocated for the specific time slot train everyday or more
TrainIDforDifDay = trains%>%
  filter(line=="Northeast Corrdr",train_id==7824,stop_sequence=="2")%>%
  arrange(date,to)%>%
  dplyr::select(scheduled_time,train_id,from,to,line)
TrainIDforDifDay = TrainIDforDifDay[1:5,]

kable(TrainIDforDifDay,align = 'c',caption = '<center>Table.A TrainID is allocated for the specific time slot everyday')%>%
  kable_classic(full_width = T)%>%
  kable_styling(position = "center",font_size = 12)%>%
  column_spec(2, background = palette1_assist)%>%
  column_spec(1,background = palette1_main)
```

```{r illustrate trainID and express line, echo=FALSE}
kable(trainIDforWholeTrip,align = 'c',caption = '<center>Table.A trainID for a whole trip</center>')%>%
  kable_classic(full_width = T)%>%
  kable_styling(position = "center",font_size = 12)%>%
  column_spec(2, background = palette1_assist)%>%
  column_spec(3, background = palette1_main)
```

```{r illustrate trainID and express line, echo=FALSE}
kable(difTrainIDs,align = 'c',caption = '<center>Table.Different TrainIDs within the same day & Express or normal lines</center>')%>%
  kable_classic(full_width = T)%>%
  kable_styling(position = "center",font_size = 12)%>%
  column_spec(2, background = palette1_assist)%>%
  row_spec(2, background = palette1_main)%>%
  row_spec(3, background = palette1_main)
```

```{r illustrate trainID and express line, echo=FALSE}
kable(TrainIDforDifDay,align = 'c',caption = '<center>Table.A TrainID is allocated for the specific time slot everyday</center>')%>%
  kable_classic(full_width = T)%>%
  kable_styling(position = "center",font_size = 12)%>%
  column_spec(2, background = palette1_assist)%>%
  column_spec(1,background = palette1_main)
```

```{r distinguish sublines, eval = FALSE}
# Distinguish Express and normal lines
# When stop_sequence == 1, certain possibilities for uptown direction, certain for downtown
trains = trains%>%
  filter(from != to)%>%
  filter(from !="secaucus concourse" & to!="secaucus upper lvl")%>%
  filter(from !="east orange" & to!="brick church")%>%
  filter(from !="new york penn station" & to!="maplewood")
# Why add this chunk?

lineList = unique(trains$line)
for (k in lineList) {
  LineTool = trains%>%
    filter(line==k,stop_sequence=="2")%>%
    arrange(date,train_id)%>%
    group_by(from,to,train_id)%>%
    summarise()
  listFrom = unique(LineTool$from)
  listTo = unique(LineTool$to)
  n = 1
  for (i in listFrom){
    for (j in listTo) {
      EvLine = filter(LineTool,from==i & to==j)
      listTrainID = unique(EvLine$train_id)
      if (length(listTrainID>0)){
        trains = trains%>%mutate(line = case_when(train_id %in% listTrainID ~ paste(line,n, sep = "_subline_"),TRUE ~ line))
        print(c(n,i,j))
        n = n+1}}}}

unique(trains$line)

trains_analysis_subline <- as.data.frame(unique(trains_analysis_subline$line))%>%
  rename("sublineList" = "unique(trains_analysis_subline$line)")%>%
  arrange(sublineList)

i=1
a=1
tableForSublines <- data.frame(matrix(NA,nrow=10))
tmp1  <- trains_analysis_subline[c(1:3),]
tmp2  <- trains_analysis_subline[c(4:9),]
tmp3  <- trains_analysis_subline[c(10:14),]
tmp4  <- trains_analysis_subline[c(15:19),]
tmp5  <- trains_analysis_subline[20,]
tmp6  <- trains_analysis_subline[c(21:27),]
tmp7  <- trains_analysis_subline[c(28:36),]
tmp8  <- trains_analysis_subline[c(37:43),]
tmp9  <- trains_analysis_subline[c(44:50),]
tmp10  <- trains_analysis_subline[c(51:53),]
tmp11  <- trains_analysis_subline[c(54:59),]
length(tmp1) = length(c(1:10))
length(tmp2) = length(c(1:10))
length(tmp3) = length(c(1:10))
length(tmp4) = length(c(1:10))
length(tmp5) = length(c(1:10))
length(tmp6) = length(c(1:10))
length(tmp7) = length(c(1:10))
length(tmp8) = length(c(1:10))
length(tmp9) = length(c(1:10))
length(tmp10) = length(c(1:10))
length(tmp11) = length(c(1:10))
tableForSublines <- cbind(tableForSublines, tmp5) 
tableForSublines <- cbind(tableForSublines, tmp10) 
tableForSublines <- cbind(tableForSublines, tmp1) 
tableForSublines <- cbind(tableForSublines, tmp3) 
tableForSublines <- cbind(tableForSublines, tmp4) 
tableForSublines <- cbind(tableForSublines, tmp2) 
tableForSublines <- cbind(tableForSublines, tmp11) 
tableForSublines <- cbind(tableForSublines, tmp6) 
tableForSublines <- cbind(tableForSublines, tmp8) 
tableForSublines <- cbind(tableForSublines, tmp9) 
tableForSublines <- cbind(tableForSublines, tmp7) 

tableForSublines = tableForSublines[1:9,2:12]
tableForSublines[is.na(tableForSublines)] = ""
kable(tableForSublines,align = 'c',caption = '<center>Table.XXX')%>%
  kable_classic(full_width = T)%>%
  kable_styling(position = "center",font_size = 12)
```

```{r}
# When stop_sequence == 1, certain possibilities for uptown direction, certain for downtown

# trains_analysis_subline = trains%>%
#   filter(from != to)%>%
#   filter(from !="secaucus concourse" & to!="secaucus upper lvl")%>%
#   filter(from !="east orange" & to!="brick church")%>%
#   filter(from !="new york penn station" & to!="maplewood")
# 
# 
# LineTool = trains_analysis_subline%>%
#     filter(line=="Northeast Corrdr",stop_sequence=="1")%>%
#     arrange(date,train_id)%>%
#     group_by(from,to,train_id)%>%
#     summarise()
# listFrom = c("new york penn station")
# # sum(trains$from == "jefferson")
# a=unique(trains%>%filter(line=="Northeast Corrdr",stop_sequence=="1")%>%dplyr::select(from))
# 
# EvLine = filter(LineTool,from %in% listFrom)
# listTrainID = unique(EvLine$train_id)
# trains_analysis_subline = trains_analysis_subline%>%mutate(line = case_when(train_id %in% listTrainID ~ paste(line,"_From",sep = ""),
#                                                                             TRUE ~line))
# 
# unique(trains_analysis_subline$line)

```

```{r delay_lag_2_hours for the specific line, eval = FALSE}
# Delays on this line two hours prior

# Add a field: time of prediction
trains = trains %>%
  mutate(timeOfPrediction = scheduled_time - hours(2))

timeLagBase = 
  trains %>%
  dplyr::select(date, line, actual_time, delay_minutes)

findLagDelay = function(timeOfPrediction, line, date){
  narrowDown = 
    timeLagBase[timeLagBase$line == line &
                  timeLagBase$date == date &
                  difftime(timeOfPrediction,
                           timeLagBase$actual_time,
                           units = 'secs') > 0,] %>%
    arrange(desc(actual_time))
  return(narrowDown[1, 4])
}

# Add lag delay data
for(i in 1:nrow(trains)){
  date = trains[i, 'date']
  line = trains[i, 'line']
  timeOfPrediction = trains[i, 'timeOfPrediction']
  lagDelay = findLagDelay(timeOfPrediction, line, date)
  trains[i, 'lagDelay'] = lagDelay
  if(i %% 1000 == 0){
    print(i)
  }
}


# Station-based average delay (2-hour lag)
```

```{r delay station average 2 hours, eval = FALSE}
stationAvgDelayBase = trainsWithoutNA %>% 
  dplyr::select(station = to, actual_time, delay_minutes) %>%
  mutate(actual_time = ymd_hms(actual_time))

findAvgStationDelay = function(timeOfPrediction, depStation){
  narrowDown = 
    stationAvgDelayBase %>%
    filter(., station == depStation &
             actual_time %within% interval(
                            timeOfPrediction - hours(1), timeOfPrediction
                          ))
  return(mean(narrowDown$delay_minutes, na.rm = T))
}

# Add station lag delay data
# This station
for(i in 1:nrow(trains)){
  depStation = trains[i, 'to']
  timeOfPrediction = trains[i, 'timeOfPrediction']
  stationDelay = findAvgStationDelay(timeOfPrediction, depStation)
  trains[i, 'stationDelay'] = stationDelay
  if(i %% 1000 == 0){
    print(i)
  }
}

```

```{r delay station average 2 hours lag 1 station, eval = FALSE}
# The last station
for(i in 1:nrow(trains)){
  depStation = trains[i, 'from']
  timeOfPrediction = trains[i, 'timeOfPrediction']
  lag1StationDelay = findAvgStationDelay(timeOfPrediction, depStation)
  trains[i, 'lag1StationDelay'] = lag1StationDelay
  if(i %% 1000 == 0){
    print(i)
  }
}
```

```{r delay station average 2 hours lag 2 stations, eval = FALSE}
lastStation = 
  trainsWithoutNA %>%
  dplyr::select(date, train = train_id, sequence = stop_sequence, lag2Station = from) %>%
  mutate(sequencePlus = sequence + 1) %>%
  dplyr::select(-sequence)

trainsWithoutNA = trains %>% filter(., !is.na(stop_sequence))

trainsTest =
  left_join(trainsWithoutNA, lastStation, by = c('date' = 'date',
                                'train_id' = 'train',
                                'stop_sequence' = 'sequencePlus')) %>%
  mutate(lag2Station = ifelse(is.na(lag2Station), from, lag2Station))


for(i in 1:nrow(trains)){
  depStation = trains[i, 'lag2Station']
  timeOfPrediction = trains[i, 'timeOfPrediction']
  lag2StationDelay = findAvgStationDelay(timeOfPrediction, depStation)
  trains[i, 'lag2StationDelay'] = lag2StationDelay
  if(i %% 1000 == 0){
    print(i)
  }
}

write.csv(trains, 'trains.csv')

trains = read.csv('trains.csv') %>% dplyr::select(-X) %>%
  mutate(timeOfPrediction = ymd_hms(timeOfPrediction),
         date = ymd(date),
         scheduled_time = ymd_hms(scheduled_time),
         actual_time = ymd_hms(actual_time))
```

```{r weather_stations}
# Weather
network = riem_networks()
weatherStations = riem_stations(network = 'NJ_ASOS') %>%
  st_as_sf(coords = c('lon', 'lat'), crs = 4326, agr = 'constant') %>%
  st_transform(crs)
weatherStations$weatherStationIndex = row.names(weatherStations) %>% as.numeric()

mapview(weatherStations) + mapview(njStations)
mapview(njStations)

njStations$weatherStationIndex =
  get.knnx(
  st_coordinates(weatherStations), 
  st_coordinates(njStations), 1)$nn.index

# Determine which weather station for which transit station
njStations = njStations %>%
  left_join(st_drop_geometry(weatherStations) %>%
              dplyr::select(weatherStationID = id, weatherStationIndex), 
            by = 'weatherStationIndex')
```

```{r join_station_info}

# trains$lagDelay = trains$lagDelay %>%
#   replace(is.na(.), 0)

trains = trains %>%
  filter(., to != 'secaucus concourse') %>%
  left_join(njStations, by = c('to' = 'station')) %>%
  st_sf() %>%
  dplyr::select(-joined, -weatherStationIndex)

```

```{r make panel, eval = FALSE}
# 
# trainsTimeInterval = 
#   trains %>%
#   mutate(timeHour = floor_date(trains3$scheduledTime, unit = 'hour'))
# 
# # All the involved stations
# 
# stations = trainsTimeInterval %>%
#   dplyr::select(station = to, geometry) %>%
#   unique()
# 
# # All the involved hour intervals
# 
# allIntervals = 
#   seq(ymd_hms('2019-09-01 00:00:00'), ymd_hms('2019-11-01 02:00:00'), by = 'hour')
# 
# # Create empty hour-station panel
# panel = 
#   expand.grid(hour = allIntervals,
#               station = stations$station) %>%
#   left_join(stations, by = 'station') %>%
#   st_sf() %>%
#   mutate(week = week(hour),
#          dayOfWeek = wday(hour, label = T))
# 
# delayAgg = trainsTimeInterval %>%
#   group_by(timeHour, to) %>%
#   summarize(avgDelay = mean(delay_minutes))
# 
# delayPanel = panel %>%
#   left_join(st_drop_geometry(delayAgg),
#             by = c('hour' = 'timeHour',
#                    'station' = 'to')) %>%
#   replace(is.na(.), 0)
# 
# # Or maybe it should not be a panel after all
# # But rather from three hours prior to two hours prior
```

```{r time_fixed_effects}

# Add time fixed effect & Select weeks
trains2 = trains %>%
  mutate(hour = hour(scheduled_time),
         dayOfWeek = wday(scheduled_time),
         week = week(scheduled_time))
  # filter(week %in% c(36:43))%>%
  # mutate(legend = case_when(
  #   week %in% c(36:41) ~ "train",
  #   TRUE ~ "test"))
```

```{r lag_one_day, eval = FALSE}
# Lag one day
trains3 = 
  trains2 %>%
  group_by(train_id, to) %>%
  arrange(scheduled_time) %>%
  mutate(lagDelayDayPlus = lag(delay_minutes, 1)) %>%
  ungroup() %>%
  mutate(actualTime = ymd_hms(actual_time),
         scheduledTime = ymd_hms(scheduled_time),
         date = ymd(date)) %>%
  rename(delay = delay_minutes, train = train_id) %>%
  dplyr::select(-actual_time, -scheduled_time,
                -to_id, -from_id)%>%
  filter(week %in% c(37:43))%>%
  mutate(legend = case_when(
    week %in% c(37:41) ~ "train",
    TRUE ~ "test"))
```

```{r weather_information}

weatherStationList = unique(trains3$weatherStationID)

weather = data.frame()
for(i in weatherStationList){
  weatherSeg = riem_measures(station = i, 
                          date_start = '2019-09-01',
                          date_end = '2019-10-31') %>%
    mutate_if(is.character, list(~replace(as.character(.), is.na(.), "0"))) %>%
    replace(is.na(.), 0) %>%
    mutate(hour = ymd_h(substr(valid, 1, 13))) %>%
    mutate(week = week(hour),
           dayOfWeek = wday(hour, label = T)) %>%
    group_by(hour) %>%
    summarize(temp = max(tmpf),
              precip = sum(p01i),
              windSpeed = max(sknt)) %>%
    mutate(temp = ifelse(temp == 0, 42, temp)) %>%
    mutate(precip = ifelse(precip > 0.2, 'Rain/Snow', 'None')) %>%
    mutate(weatherStationID = i)
  weather = rbind(weather, weatherSeg)
}

```

```{r join_weather}
# Floor time
trains3$timeHour = floor_date(trains3$scheduledTime, unit = 'hour')

trains4 = trains3 %>%
  left_join(weather,
            by = c('weatherStationID' = 'weatherStationID',
                   'timeHour' = 'hour'))
```

```{r distance to first station}

trainIDAndfirstStations = trains4 %>%
  filter(., stop_sequence == 1) %>%
  dplyr::select(firstStation = to, train) %>%
  unique()

firstStations = trainIDAndfirstStations %>%
  dplyr::select(firstStation) %>%
  unique()

distanceMatrix = 
  expand.grid(firstStation = firstStations$firstStation,
              station = stations$station)

for(i in 1:nrow(distanceMatrix)){
  thisFirstStation = distanceMatrix[i, 1]
  thisStation = distanceMatrix[i, 2]
  distance = st_distance(
    firstStations %>% filter(., firstStation == thisFirstStation),
    stations %>% filter(., station == thisStation)
  ) %>% as.numeric()
  distanceMatrix[i, 'distance'] = distance
  if(i %% 100 == 0){
    print(i)
  }
}

trainIDAndStations = trains4 %>%
  dplyr::select(station = to, train) %>%
  unique() %>%
  left_join(trainIDAndfirstStations %>% st_drop_geometry,
            by = 'train') %>%
  left_join(distanceMatrix, by = c('firstStation' = 'firstStation',
                                   'station' = 'station'))

trains5 = trains4 %>%
  left_join(st_drop_geometry(trainIDAndStations) %>%
              dplyr::select(-firstStation),
            by = c('to' = 'station',
                   'train' = 'train')) %>%
  rename(distFirstStation = distance)

```

```{r distance to new york penn}

NYPennStation = stations %>%
  filter(., station == 'new york penn')

stations = stations %>%
  mutate(distNYPenn = 
           st_distance(., NYPennStation) %>% as.numeric())

trains5 = trains4 %>%
  left_join(st_drop_geometry(trainIDAndStations) %>%
              dplyr::select(-firstStation),
            by = c('to' = 'station',
                   'train' = 'train')) %>%
  rename(distFirstStation = distance)

trains6 = trains5 %>%
  left_join(st_drop_geometry(stations) %>%
              rename(lastStationDistNYPenn = distNYPenn),
            by = c('from' = 'station')) %>%
  left_join(st_drop_geometry(stations) %>%
              rename(thisStationDistNYPenn = distNYPenn),
            by = c('to' = 'station')) %>%
  mutate(direction = 
           ifelse(lastStationDistNYPenn > thisStationDistNYPenn,
                  'downtown', 'uptown'))

trains6 = trains6 %>%
  mutate(lagDelay = tidyr::replace_na(lagDelay, 0),
         stationDelay = tidyr::replace_na(stationDelay, 0),
         lag1StationDelay = tidyr::replace_na(lag1StationDelay, 0),
         lag2StationDelay = tidyr::replace_na(lag2StationDelay, 0),
         lagDelayDayPlus = tidyr::replace_na(lagDelayDayPlus, 0),
         dayOfWeek = as.character(dayOfWeek),
         hour = as.character(hour))

```

```{r model prep}

st_write(trains6, 'trains6.GeoJson')

trainsTrain = trains6 %>%
  filter(., legend == 'train')

stationHourMean = trainsTrain %>%
  group_by(to, hour) %>%
  summarize(meanDelay = mean(delay, na.rm = T)) %>%
  mutate(stationHour10Tile = ntile(meanDelay, 10) %>% as.character()) %>%
  st_drop_geometry() %>%
  mutate(hour = as.character(hour))

trainsTrain = trainsTrain %>%
  left_join(stationHourMean %>% dplyr::select(-meanDelay),
            by = c('to' = 'to',
                   'hour' = 'hour'))

trainsTest = trains6 %>%
  filter(., legend == 'test') %>%
  left_join(stationHourMean %>% dplyr::select(-meanDelay),
            by = c('to' = 'to',
                   'hour' = 'hour'))
```

```{r baseline models, fig.height = 9, fig.width = 9}
# Baseline

reg2h = lm(delay ~ 
               stop_sequence + to + line + lagDelay + stationDelay +
               lag1StationDelay + lag2StationDelay + lagDelayDayPlus +
               hour + dayOfWeek + precip,
             data = trainsTrain)

reg2hWTile = lm(delay ~ 
               stop_sequence + to + line + lagDelay + stationDelay +
               lag1StationDelay + lag2StationDelay + lagDelayDayPlus +
               hour + dayOfWeek + precip + stationHour10Tile,
             data = trainsTrain)

reg2hWTileWDist = lm(delay ~ 
               stop_sequence + to + line + lagDelay + stationDelay +
               lag1StationDelay + lag2StationDelay + lagDelayDayPlus +
               hour + dayOfWeek + precip + stationHour10Tile + distFirstStation,
             data = trainsTrain)

reg2hWDir = lm(delay ~ 
               stop_sequence + to + line + lagDelay + stationDelay +
               lag1StationDelay + lag2StationDelay + lagDelayDayPlus +
               hour + dayOfWeek + precip + direction,
             data = trainsTrain)

reg2hWTileWDir = lm(delay ~ 
               stop_sequence + to + line + lagDelay + stationDelay +
               lag1StationDelay + lag2StationDelay + lagDelayDayPlus +
               hour + dayOfWeek + precip + stationHour10Tile + direction,
             data = trainsTrain)

trainsTest = trainsTest %>%
  mutate(predict2h = predict(reg2h, newdata = trainsTest),
         absError2h = abs(delay - predict2h))

trainsTest = trainsTest %>%
  mutate(predict2hWTile = predict(reg2hWTile, newdata = trainsTest),
         absError2hWTile = abs(delay - predict2hWTile))

trainsTest = trainsTest %>%
  mutate(predict2hWTileWDist = predict(reg2hWTileWDist, newdata = trainsTest),
         absError2hWTileWDist = abs(delay - predict2hWTileWDist))

trainsTest = trainsTest %>%
  mutate(predict2hWTileWDir = predict(reg2hWTileWDir, newdata = trainsTest),
         absError2hWTileWDir = abs(delay - predict2hWTileWDir))

trainsTest = trainsTest %>%
  mutate(predict2hWDir = predict(reg2hWDir, newdata = trainsTest),
         absError2hWDir = abs(delay - predict2hWDir))

ggplot(trainsTest %>% sample_n(10000)) +
  geom_point(aes(x = delay, y = predict2hWDir), color = brightRed) +
  geom_abline(slope = 1, intercept = 0, color = "gray", size = 1) +
  labs(x = "Actual delay (min)", y = "Predicted delay (min)") +
  presentPlotTheme() +
  theme(axis.title.y = element_text(vjust=2))

mean(trainsTest$absError2hWDir, na.rm = T)

ggplot(trains6) +
  geom_histogram(aes(delay), fill = brightRed, bins = 100)+
  presentPlotTheme() +
  labs(x = "Delay", y = "Count") +
  theme(axis.text.y = element_blank())
```

```{r log model, eval = FALSE, fig.height = 9, fig.width = 9}
# log the dependent (not good)

trainsTrain = trainsTrain %>%
  mutate(logDelay = log(delay + 1))

reg2hLogWTileWDir = lm(logDelay ~ 
               stop_sequence + to + line + lagDelay + stationDelay +
               lag1StationDelay + lag2StationDelay + lagDelayDayPlus +
               hour + dayOfWeek + precip + direction + stationHour10Tile,
             data = trainsTrain)

trainsTest = trainsTest %>%
  mutate(logPredictLogWTileWDir = predict(reg2hLogWTileWDir, newdata = trainsTest),
         predict2hLogWTileWDir = exp(logPredictLogWTileWDir) - 1,
         absError2hLogWTileWDir = abs(delay - predict2hLogWTileWDir))

ggplot(trainsTest) +
  geom_point(aes(x = delay, y = predict2hLogWTileWDir))

ggplot(trainsTest %>% sample_n(10000)) +
  geom_point(aes(x = delay, y = predict2hLogWTileWDir), color = brightRed,
             size = 2) +
  geom_abline(slope = 1, intercept = 0, color = "gray", size = 1) +
  labs(x = "Actual delay (min)", y = "Predicted delay (min)") +
  presentPlotTheme() +
  theme(axis.title.y = element_text(vjust=2))

mean(trainsTest$absError2hSqWTileWDir, na.rm = T)
```

```{r sq model}
# sq the dependent

trainsTrain = trainsTrain %>%
  mutate(sqDelay = sqrt(delay))

reg2hLnSq = lm(sqDelay ~ 
               stop_sequence + to + line + lagDelay + stationDelay +
               lag1StationDelay + lag2StationDelay + lagDelayDayPlus +
               hour + dayOfWeek + precip,
             data = trainsTrain)

reg2hLnSqWTile = lm(sqDelay ~ 
               stop_sequence + to + line + lagDelay + stationDelay +
               lag1StationDelay + lag2StationDelay + lagDelayDayPlus +
               hour + dayOfWeek + precip + stationHour10Tile,
             data = trainsTrain)

reg2hLnSqWTileWDist = lm(sqDelay ~ 
               stop_sequence + to + line + lagDelay + stationDelay +
               lag1StationDelay + lag2StationDelay + lagDelayDayPlus +
               hour + dayOfWeek + precip + stationHour10Tile + distFirstStation,
             data = trainsTrain)

reg2hLnSqWTileWDir = lm(sqDelay ~ 
               stop_sequence + to + line + lagDelay + stationDelay +
               lag1StationDelay + lag2StationDelay + lagDelayDayPlus +
               hour + dayOfWeek + precip + stationHour10Tile + direction,
             data = trainsTrain)


trainsTest = trainsTest %>%
  mutate(sqPredict2hSq = predict(reg2hLnSq, newdata = trainsTest),
         predict2hSq = sqPredict2hSq ^ 2,
         absError2hSq = abs(delay - predict2hSq))

trainsTest = trainsTest %>%
  mutate(sqPredict2hSqWTile = predict(reg2hLnSqWTile, newdata = trainsTest),
         predict2hSqWTile = sqPredict2hSqWTile ^ 2,
         absError2hSqWTile = abs(delay - predict2hSqWTile))

trainsTest = trainsTest %>%
  mutate(sqPredict2hSqWTileWDist = predict(reg2hLnSqWTileWDist, newdata = trainsTest),
         predict2hSqWTileWDist = sqPredict2hSqWTileWDist ^ 2,
         absError2hSqWTileWDist = abs(delay - predict2hSqWTileWDist))

trainsTest = trainsTest %>%
  mutate(sqPredict2hSqWTileWDir = predict(reg2hLnSqWTileWDir, newdata = trainsTest),
         predict2hSqWTileWDir = sqPredict2hSqWTileWDir ^ 2,
         absError2hSqWTileWDir = abs(delay - predict2hSqWTileWDir))

ggplot(trainsTest) +
  geom_point(aes(x = delay, y = predict2hSqWTile))

```

```{r square models both, eval = FALSE}
# sq both the dependent and the independent (not good)

ggplot(trainsTrain) +
  geom_histogram(aes(x = stationDelay))

reg2hLnSqAll = lm(sqDelay ~ 
                 stop_sequence + to + line + I(sqrt(lagDelay)) + 
                 I(sqrt(stationDelay)) + I(sqrt(lag1StationDelay)) +
                 I(sqrt(lag2StationDelay)) + I(sqrt(lagDelayDayPlus)) +
                 hour + dayOfWeek + precip,
               data = trainsTrain)

trainsTest = trainsTest %>%
  mutate(sqPredict2hSqAll = predict(reg2hLnSqAll, newdata = trainsTest),
         predict2hSqAll = sqPredict2hSqAll ^ 2,
         absError2hSqAll = abs(delay - predict2hSqAll))

ggplot(trainsTest) +
  geom_point(aes(x = delay, y = predict2hSqAll))
```

```{r square models with square independents}
# sq the dependent, and some independents squared 

ggplot(trainsTrain) +
  geom_histogram(aes(x = stationDelay))

reg2hLnSqSq = lm(sqDelay ~
                   stop_sequence + to + line + lagDelay + I(lagDelay ^ 2) + stationDelay +
                   I(stationDelay ^ 2) + lag1StationDelay + I(lag1StationDelay ^ 2) +
                   lag2StationDelay + I(lag2StationDelay ^ 2) + lagDelayDayPlus +
                   I(lagDelayDayPlus ^ 2) +
                   hour + dayOfWeek + precip,
                 data = trainsTrain)

reg2hLnSqSqWTile = lm(sqDelay ~
                   stop_sequence + to + line + lagDelay + I(lagDelay ^ 2) + stationDelay +
                   I(stationDelay ^ 2) + lag1StationDelay + I(lag1StationDelay ^ 2) +
                   lag2StationDelay + I(lag2StationDelay ^ 2) + lagDelayDayPlus +
                   I(lagDelayDayPlus ^ 2) +
                   hour + dayOfWeek + precip + stationHour10Tile,
                 data = trainsTrain)

reg2hLnSqSqWTileWDist = lm(sqDelay ~
                   stop_sequence + to + line + lagDelay + I(lagDelay ^ 2) + stationDelay +
                   I(stationDelay ^ 2) + lag1StationDelay + I(lag1StationDelay ^ 2) +
                   lag2StationDelay + I(lag2StationDelay ^ 2) + lagDelayDayPlus +
                   I(lagDelayDayPlus ^ 2) +
                   hour + dayOfWeek + precip + stationHour10Tile + distFirstStation,
                 data = trainsTrain)

reg2hLnSqSqWTileWDir = lm(sqDelay ~
                   stop_sequence + to + line + lagDelay + I(lagDelay ^ 2) + stationDelay +
                   I(stationDelay ^ 2) + lag1StationDelay +
                   lag2StationDelay + lagDelayDayPlus +
                     hour + dayOfWeek + precip + stationHour10Tile + direction,
                 data = trainsTrain)

trainsTest = trainsTest %>%
  mutate(sqPredict2hSqSq = predict(reg2hLnSqSq, newdata = trainsTest),
         predict2hSqSq = sqPredict2hSqSq ^ 2,
         absError2hSqSq = abs(delay - predict2hSqSq))

trainsTest = trainsTest %>%
  mutate(sqPredict2hSqSqWTile = predict(reg2hLnSqSqWTile, newdata = trainsTest),
         predict2hSqSqWTile = sqPredict2hSqSqWTile ^ 2,
         absError2hSqSqWTile = abs(delay - predict2hSqSqWTile))

trainsTest = trainsTest %>%
  mutate(sqPredict2hSqSqWTileWDist = predict(reg2hLnSqSqWTileWDist, newdata = trainsTest),
         predict2hSqSqWTileWDist = sqPredict2hSqSqWTileWDist ^ 2,
         absError2hSqSqWTileWDist = abs(delay - predict2hSqSqWTileWDist))

trainsTest = trainsTest %>%
  mutate(sqPredict2hSqSqWTileWDir = predict(reg2hLnSqSqWTileWDir, newdata = trainsTest),
         predict2hSqSqWTileWDir = sqPredict2hSqSqWTileWDir ^ 2,
         absError2hSqSqWTileWDir = abs(delay - predict2hSqSqWTileWDir))

ggplot(trainsTest) +
  geom_point(aes(x = delay, y = predict2h)) +
  geom_abline(slope = 1, intercept = 0)
ggplot(trainsTest) +
  geom_point(aes(x = delay, y = predict2hSqWTileWDir)) +
  geom_abline(slope = 1, intercept = 0)



mean(trainsTest$absError2h, na.rm = T)
mean(trainsTest$absError2hWTile, na.rm = T)
mean(trainsTest$absError2hWTileWDist, na.rm = T)
mean(trainsTest$absError2hWTileWDir, na.rm = T)

mean(trainsTest$absError2hSq, na.rm = T)
mean(trainsTest$absError2hSqWTile, na.rm = T)
mean(trainsTest$absError2hSqWTileWDist, na.rm = T)
mean(trainsTest$absError2hSqWTileWDir, na.rm = T)

mean(trainsTest$absError2hSqSq, na.rm = T)
mean(trainsTest$absError2hSqSqWTile, na.rm = T)
mean(trainsTest$absError2hSqSqWTileWDist, na.rm = T)
mean(trainsTest$absError2hSqSqWTileWDir, na.rm = T)
```

```{r late-or-not logit reg, eval = FALSE}

#Not good

ggplot(trainsTrain) +
  geom_histogram(aes(delay), bins = 50)

trainsTrain = trainsTrain %>%
  mutate(late = ifelse(delay > 10, 1, 0))
trainsTest = trainsTest %>%
  mutate(late = ifelse(delay > 10, 1, 0))
# table(trainsTrain$late)
lateOrNot = glm(late ~ 
                  stop_sequence + to + line + lagDelay + stationDelay +
                  lag1StationDelay + lag2StationDelay + lagDelayDayPlus +
                  hour + dayOfWeek + precip + stationHour10Tile + distFirstStation,
                data = trainsTrain,
                family="binomial" (link="logit"))

lateProbs = data.frame(
  outcome = as.factor(trainsTest$late),
  probs = predict(lateOrNot, trainsTest, type = 'response')
)

ggplot(lateProbs, aes(x = probs, fill = as.factor(outcome))) +
  geom_density() +
  facet_grid(outcome ~.) +
  scale_fill_manual(values = c(color2, color3)) +
  xlim(0, 1) +
  plotTheme()
  
```

```{r different model for small delays}


reg2hLnSqWTileWDirSmall = lm(sqDelay ~
                   stop_sequence + to + line + lagDelay + stationDelay +
                     lag1StationDelay + 
                   lag2StationDelay + lagDelayDayPlus +
                   hour + dayOfWeek + precip + stationHour10Tile + direction,
                 data = trainsTrain %>% filter(., delay <= 30))

trainsTest = trainsTest %>%
  mutate(sqPredict2hSqWTileWDirSmall = 
           predict(reg2hLnSqWTileWDirSmall, newdata = trainsTest),
         predict2hSqWTileWDirSmall = sqPredict2hSqWTileWDirSmall ^ 2)

trainsTest = trainsTest %>%
  mutate(predict2hSeg = 
           ifelse(predict2hSqWTileWDir <= 20,
                  predict2hSqWTileWDirSmall,
                  predict2hSqWTileWDir),
         absError2hSeg = abs(delay - predict2hSeg))

mean(trainsTest$absError2hSqSq, na.rm = T)
mean(trainsTest$absError2hSqSqWTile, na.rm = T)
mean(trainsTest$absError2hSqSqWTileWDist, na.rm = T)
mean(trainsTest$absError2hSqWTileWDir, na.rm = T)
mean(trainsTest$absError2hSeg, na.rm = T)

ggplot(trainsTest %>% sample_n(10000)) +
  geom_point(aes(x = delay, y = predict2hSeg), size = 0.001) +
  geom_abline(slope = 1, intercept = 0)
```

```{r short term prediction, eval = FALSE}
# Delays on this line two hours prior

# Add a field: time of prediction (short-term)
trainsS = trains6 %>%
  mutate(timeOfPredictionS = scheduledTime - minutes(30)) %>%
  st_drop_geometry

# Add lag delay data (short-term)

for(i in 1:nrow(trainsS)){
  date = trainsS[[i, 'date']]
  line = trainsS[[i, 'line']]
  timeOfPredictionS = trainsS[[i, 'timeOfPredictionS']]
  lagDelayS = findLagDelay(timeOfPredictionS, line, date)
  trainsS[[i, 'lagDelayS']] = lagDelayS
  if(i %% 1000 == 0){
    print(i)
  }
}

# delay station avg short term

for(i in 1:nrow(trainsS)){
  depStation = trainsS[[i, 'to']]
  timeOfPredictionS = trainsS[[i, 'timeOfPredictionS']]
  stationDelayS = findAvgStationDelay(timeOfPredictionS, depStation)
  trainsS[[i, 'stationDelayS']] = stationDelayS
  if(i %% 1000 == 0){
    print(i)
  }
}

# The last station (short)
for(i in 1:nrow(trainsS)){
  depStation = trainsS[[i, 'from']]
  timeOfPredictionS = trainsS[[i, 'timeOfPredictionS']]
  lag1StationDelayS = findAvgStationDelay(timeOfPredictionS, depStation)
  trainsS[[i, 'lag1StationDelayS']] = lag1StationDelayS
  if(i %% 1000 == 0){
    print(i)
  }
}

# The last before the last station (short)
for(i in 1:nrow(trainsS)){
  depStation = trainsS[[i, 'lag2Station']]
  timeOfPredictionS = trains[[i, 'timeOfPredictionS']]
  lag2StationDelayS = findAvgStationDelay(timeOfPredictionS, depStation)
  trainsS[[i, 'lag2StationDelayS']] = lag2StationDelayS
  if(i %% 1000 == 0){
    print(i)
  }
}

trainsS = trainsS %>%
  mutate(lagDelayS = tidyr::replace_na(lagDelayS, 0),
         stationDelayS = tidyr::replace_na(stationDelayS, 0),
         lag1StationDelayS = tidyr::replace_na(lag1StationDelayS, 0),
         lag2StationDelayS = tidyr::replace_na(lag2StationDelayS, 0),
         lagDelayDayPlus = tidyr::replace_na(lagDelayDayPlus, 0))

write.csv(trainsS, 'trainsS.csv')
trainsS = read.csv('trainsS.csv') %>%
  mutate(hour = as.character(hour),
         dayOfWeek = as.character(dayOfWeek),
         date = ymd(date))

trainsTrainS = trainsS %>%
  filter(., legend == 'train')

trainsTrainS = trainsTrainS %>%
  left_join(stationHourMean %>% dplyr::select(-meanDelay),
            by = c('to' = 'to',
                   'hour' = 'hour'))
trainsTestS = trainsS %>%
  filter(., legend == 'test') %>%
  left_join(stationHourMean %>% dplyr::select(-meanDelay),
            by = c('to' = 'to',
                   'hour' = 'hour'))


trainsTrainS = trainsTrainS %>%
  mutate(sqDelay = sqrt(delay))

reg30mSqWTileWDir = lm(sqDelay ~ 
               stop_sequence + to + line + lagDelayS + stationDelayS +
               lag1StationDelayS + lag2StationDelayS + lagDelayDayPlus +
               hour + dayOfWeek + precip + stationHour10Tile + direction,
             data = trainsTrainS)

reg30mWDir = lm(delay ~ 
               stop_sequence + to + line + lagDelayS + stationDelayS +
               lag1StationDelayS + lag2StationDelayS + lagDelayDayPlus +
               hour + dayOfWeek + precip + direction,
             data = trainsTrainS)

reg30mSqWTileWDirSmall = lm(sqDelay ~
                   stop_sequence + to + line + lagDelayS + stationDelayS +
                     lag1StationDelayS + 
                   lag2StationDelayS + lagDelayDayPlus +
                   hour + dayOfWeek + precip + stationHour10Tile + direction,
                 data = trainsTrainS %>% filter(., delay <= 30))

trainsTestS = trainsTestS %>%
  mutate(predict30mWDir = predict(reg30mWDir, newdata = trainsTestS),
         absError30mWDir = abs(delay - predict30mWDir))

mean(trainsTestS$absError30mWDir, na.rm = T)

trainsTestS = trainsTestS %>%
  mutate(sqPredict30mSqWTileWDir = predict(reg30mSqWTileWDir, newdata = trainsTestS),
         predict30mSqWTileWDir = sqPredict30mSqWTileWDir ^ 2,
         absError30mSqWTileWDir = abs(delay - predict30mSqWTileWDir),
         sqPredict30mSqWTileWDirSmall = predict(reg30mSqWTileWDirSmall,
                                                newdata = trainsTestS),
         predict30mSqWTileWDirSmall = sqPredict30mSqWTileWDirSmall ^ 2,
         predict30mSeg = ifelse(predict30mSqWTileWDir < 20,
                                predict30mSqWTileWDirSmall,
                                predict30mSqWTileWDir),
         absError30mSeg = abs(delay - predict30mSeg))

ggplot(trainsTestS %>% sample_n(10000)) +
  geom_point(aes(x = delay, y = predict30mSqWTileWDir), size = .001)

ggplot(trainsTestS %>% sample_n(10000)) +
  geom_point(aes(x = delay, y = predict30mSeg), size = .001)

ggplot(trainsTest %>% sample_n(10000)) +
  geom_point(aes(x = delay, y = predict2hSqWTileWDirS), size = .001)


  

```

```{r cross validation by day, fig.height = 9}

trainsL = trains6 %>%
  mutate(sqDelay = sqrt(delay)) %>%
  left_join(stationHourMean %>% dplyr::select(-meanDelay),
            by = c('to' = 'to',
                   'hour' = 'hour'))
trainsS = trainsS %>%
  mutate(sqDelay = sqrt(delay)) %>%
  left_join(stationHourMean %>% dplyr::select(-meanDelay),
            by = c('to' = 'to',
                   'hour' = 'hour'))
dateList = unique(trainsL$date)

MAE2hList = list()
MAE30mList = list()
dayNoList = list()
for (dayNo in dateList){
  gc()
  
  dayNoList = append(dayNoList, dayNo)
  cat('This hold-out test day is', dayNo, '\n')
  daysTrainL = trainsL %>% filter(., date != dayNo) %>% as.data.frame()
  daysTestL = trainsL %>% filter(., date == dayNo) %>% as.data.frame()
  daysTrainS = trainsS %>% filter(., date != dayNo) %>% as.data.frame()
  daysTestS = trainsS %>% filter(., date == dayNo) %>% as.data.frame()
  
  reg2h = lm(sqDelay ~ 
               stop_sequence + to + line + lagDelay + stationDelay +
               lag1StationDelay + lag2StationDelay + lagDelayDayPlus +
               hour + dayOfWeek + precip + stationHour10Tile + direction,
             data = daysTrainL)
  reg2hSmall = lm(sqDelay ~ 
               stop_sequence + to + line + lagDelay + stationDelay +
               lag1StationDelay + lag2StationDelay + lagDelayDayPlus +
               hour + dayOfWeek + precip + stationHour10Tile + direction,
             data = daysTrainL %>% filter(., delay <= 30))
  
  reg30m = lm(sqDelay ~ 
               stop_sequence + to + line + lagDelayS + stationDelayS +
               lag1StationDelayS + lag2StationDelayS + lagDelayDayPlus +
               hour + dayOfWeek + precip + stationHour10Tile + direction,
             data = daysTrainS)
  
  reg30mSmall = lm(sqDelay ~ 
               stop_sequence + to + line + lagDelayS + stationDelayS +
               lag1StationDelayS + lag2StationDelayS + lagDelayDayPlus +
               hour + dayOfWeek + precip + stationHour10Tile + direction,
             data = daysTrainS %>% filter(., delay <= 30))

  testCompareL = data.frame(observation = daysTestL$delay,
                            sqPrediction = predict(reg2h, newdata = daysTestL),
                            sqPredictionSmall = 
                              predict(reg2hSmall, newdata = daysTestL)) %>%
    mutate(prediction = sqPrediction ^ 2,
           predictionSmall = sqPredictionSmall ^ 2,
           prediction = ifelse(
             prediction < 20,
             predictionSmall,
             prediction
             )) %>%
    mutate(absError = abs(observation - prediction))
  
  testCompareS = data.frame(observation = daysTestS$delay,
                            sqPrediction = predict(reg30m, newdata = daysTestS),
                            sqPredictionSmall = 
                              predict(reg30mSmall, newdata = daysTestS)) %>%
    mutate(prediction = sqPrediction ^ 2,
         predictionSmall = sqPredictionSmall ^ 2,
         prediction = ifelse(
           prediction < 20,
           predictionSmall,
           prediction
           )) %>%
    mutate(absError = abs(observation - prediction))
  
  MAE2h = mean(testCompareL$absError, na.rm = T)
  MAE30m = mean(testCompareS$absError, na.rm = T)

  MAE2hList = append(MAE2hList, MAE2h)
  MAE30mList = append(MAE30mList, MAE30m)
  
  cat('The 2h-MAE is', MAE2h, '\n')
  cat('The 30m-MAE is', MAE30m, '\n')
  
}

CVResult = cbind(MAE2hList, MAE30mList) %>%
  as.data.frame() %>%
  mutate(MAE2h = MAE2hList %>% as.numeric(),
         MAE30m = MAE30mList %>% as.numeric()) %>%
  dplyr::select(-MAE2hList, -MAE30mList) %>%
  cbind(dateList) %>%
  as.data.frame() %>%
  rename(date = dateList)


CVResult %>%
  gather(model, MAE, -date) %>%
  mutate(model = recode(model, 
                        'MAE2h' = '2 hours ahead',
                        'MAE30m' = '30 minutes ahead')) %>%
  ggplot(aes(date, MAE)) +
  geom_point(aes(shape = model), size = 2) +
  scale_shape_manual(values = c(2, 17), name = '') +
  geom_line() +
  labs(x = 'Day', y = 'MAE') +
  presentPlotTheme()

```

```{r final table for comparisons}
trainsTest = trainsTest %>%
  mutate(predict2hSeg = 
           ifelse(predict2hSqWTileWDir <= 20,
                  predict2hSqWTileWDirSmall,
                  predict2hSqWTileWDir),
         absError2hSeg = abs(delay - predict2hSeg))

finalComparison = cbind(
  trainsTest %>%
    mutate(obs= delay,
           predLong = predict2hSeg,
           absErrLong = absError2hSeg,
           ) %>%
    dplyr::select(date, train, station = to, line, GEOID,
                  week, hour, dayOfWeek, obs, predLong, absErrLong),
  trainsTestS %>%
    mutate(predShort = predict30mSeg,
           absErrShort = absError30mSeg)  %>%
    dplyr::select(predShort, absErrShort)
) %>%
  left_join(counties %>% st_drop_geometry(), by = 'GEOID') %>%
  rename(county = NAMELSAD)

finalComparison1 =
  trainsTest %>%
    mutate(obs= delay,
           pred = predict2hWTileWDir,
           absErr = absError2hWTileWDir,
           ) %>%
    dplyr::select(date, train, station = to, line, GEOID,
                  week, hour, dayOfWeek, obs, pred, absErr)
  
```

```{r MAE by station by week, fig.height = 16}

presentTheme <- function(base_size = 30, title_size = 45) {
  theme(
    text = element_text(family = 'font', color = "black"),
    plot.title = element_text(hjust = 0.5, size = title_size, colour = "black",face = "bold"), 
    plot.subtitle = element_text(hjust = 0.5,size=base_size,face="italic"),
    plot.caption = element_text(size=base_size,hjust=0),
    axis.ticks = element_blank(),
    panel.spacing = unit(3, 'lines'),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=.5),
    strip.background = element_rect(fill = "grey95", color = "black"),
    strip.text = element_text(size=base_size),
    axis.title = element_text(face = "bold",size=base_size),
    axis.text = element_blank(),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(size=base_size,colour = "black", face = "italic"),
    legend.text = element_text(size=base_size,colour = "black", face = "italic"),
    strip.text.x = element_text(size = base_size,face = "bold"),
    legend.key.size = unit(2, 'line')
  )
}


byStationByWeek = 
  finalComparison %>%
  group_by(station, week) %>%
  summarize(MAE2h = mean(absErrLong, na.rm = T),
            MAE30m = mean(absErrShort, na.rm = T)) %>%
  gather(model, MAE, -station, -week, -geometry) %>%
  mutate(week = recode(week, '42' = 'Week 42', '43' = 'Week 43'),
         model = recode(model, 
                        'MAE2h' = '2 hours prior',
                        'MAE30m' = '30 minutes prior'))
byLine
byStationByWeekAnimation = 
  byStationByWeek %>%
  ggplot() +
  geom_sf(data = st_union(njCounties),
          color='black', size=1.5, fill = NA)+
  geom_sf(data = njCounties,
          color= 'black', size=0.5,linetype = 'dashed', fill = NA) +
  geom_sf(aes(color = MAE), size = 2) +
  scale_color_gradient(high = lightRed, low = darkBlue) +
  facet_wrap(model) +
  transition_manual(week) +
  presentTheme() +
  theme(legend.position = c(1.3, 0.5))

mean(trains6$delay, na.rm = T)
mean((trains6 %>% filter(., (!(dayOfWeek %in% c('1', '2')))))$delay, na.rm = T)

```

```{r MAE by station by day of week, fig.height = 16}
byStationByDayOfWeek = 
  finalComparison %>%
  group_by(station, dayOfWeek) %>%
  summarize(MAE2h = mean(absErrLong, na.rm = T),
            MAE30m = mean(absErrShort, na.rm = T)) %>%
  gather(model, MAE, -station, -dayOfWeek, -geometry) %>%
  mutate(dayOfWeek = recode(dayOfWeek, 
                       '3' = 'Mon',
                       '4' = 'Tue',
                       '5' = 'Wed',
                       '6' = 'Thu',
                       '7' = 'Fri',
                       '1' = 'Sat',
                       '2' = 'Sun') %>%
           factor(., levels = c('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun')),
         model = recode(model, 
                        'MAE2h' = '2 hours ahead',
                        'MAE30m' = '30 minutes ahead'))

byStationByDayOfWeekAnimation = 
  byStationByDayOfWeek %>%
  mutate(MAE = ifelse(MAE > 5, 5, MAE)) %>%
  ggplot() +
  geom_sf(data = st_union(njCounties),
          color='black', size=1.5, fill = NA)+
  geom_sf(data = njCounties,
          color= 'black', size=0.5,linetype = 'dashed', fill = NA) +
  geom_sf(aes(color = MAE), size = 3) +
  scale_color_gradient(high = brightRed, low = darkBlue,
                       name = '',
                       breaks = c(0, 1, 2, 3, 4, 5),
                       labels = c("0", "1", "2", "3", "4", "5+")) +
  facet_wrap(~model) +
  labs(title = '{current_frame}') +
  transition_manual(dayOfWeek) +
  presentTheme()


anim_save("byStationByDayOfWeekAnimation.gif", byStationByDayOfWeekAnimation,
          duration=7, renderer = gifski_renderer(), height = 715, width = 715)
```

```{r MAE by hour, fig.height = 24}

byStationByHour = 
  finalComparison %>%
  mutate(hour = as.numeric(hour)) %>%
  group_by(station, hour) %>%
  summarize(MAE2h = mean(absErrLong, na.rm = T),
            MAE30m = mean(absErrShort, na.rm = T)) %>%
  gather(model, MAE, -station, -hour, -geometry) %>%
  mutate(model = recode(model, 
                        'MAE2h' = '2 hours ahead',
                        'MAE30m' = '30 minutes ahead'))

byStationByHourAnimation = 
  byStationByHour %>%
  mutate(MAE = ifelse(MAE > 5, 5, MAE)) %>%
  ggplot() +
  geom_sf(data = st_union(njCounties),
          color='black', size=1.5, fill = NA)+
  geom_sf(data = njCounties,
          color= 'black', size=0.5,linetype = 'dashed', fill = NA) +
  geom_sf(aes(color = MAE), size = 3) +
  scale_color_gradient(high = brightRed, low = darkBlue,
                       name = '',
                       breaks = c(0, 1, 2, 3, 4, 5),
                       labels = c("0", "1", "2", "3", "4", "5+")) +
  facet_wrap(~model) +
  labs(title = '{current_frame}:00 ~ {current_frame}:59') +
  transition_manual(hour) +
  presentTheme()

anim_save("byStationByHourAnimation.gif", byStationByHourAnimation,
          duration=12, renderer = gifski_renderer(), height = 715, width = 715)

?facet_wrap
```

```{r MAE by line, fig.height = 9}

lines = rbind(
  st_read('https://services6.arcgis.com/M0t0HPE53pFK525U/arcgis/rest/services/NJTransit_Rail_Linea/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson') %>%
    st_transform(crs) %>%
    mutate(line = 'Northeast Corrdr') %>%
    dplyr::select(line),
  st_read('https://services6.arcgis.com/M0t0HPE53pFK525U/arcgis/rest/services/NJTransit_Rail_Linea/FeatureServer/6/query?outFields=*&where=1%3D1&f=geojson') %>%
    st_transform(crs) %>%
    mutate(line = 'Atl. City Line') %>%
    dplyr::select(line),
  st_read('https://services6.arcgis.com/M0t0HPE53pFK525U/arcgis/rest/services/NJTransit_Rail_Linea/FeatureServer/7/query?outFields=*&where=1%3D1&f=geojson') %>%
    st_transform(crs) %>%
    mutate(line = 'Bergen Co. Line ') %>%
    dplyr::select(line),
  st_read('https://services6.arcgis.com/M0t0HPE53pFK525U/arcgis/rest/services/NJTransit_Rail_Linea/FeatureServer/9/query?outFields=*&where=1%3D1&f=geojson') %>%
    st_transform(crs) %>%
    mutate(line = 'Gladstone Branch') %>%
    dplyr::select(line),
  st_read('https://services6.arcgis.com/M0t0HPE53pFK525U/arcgis/rest/services/NJTransit_Rail_Linea/FeatureServer/4/query?outFields=*&where=1%3D1&f=geojson') %>%
    st_transform(crs) %>%
    mutate(line = 'Main Line') %>%
    dplyr::select(line),
  st_read('https://services6.arcgis.com/M0t0HPE53pFK525U/arcgis/rest/services/NJTransit_Rail_Linea/FeatureServer/8/query?outFields=*&where=1%3D1&f=geojson') %>%
    st_transform(crs) %>%
    mutate(line = 'Montclair-Boonton') %>%
    dplyr::select(line),
  st_read('https://services6.arcgis.com/M0t0HPE53pFK525U/arcgis/rest/services/NJTransit_Rail_Linea/FeatureServer/3/query?outFields=*&where=1%3D1&f=geojson') %>%
    st_transform(crs) %>%
    mutate(line = 'Morristown Line') %>%
    dplyr::select(line),
  st_read('https://services6.arcgis.com/M0t0HPE53pFK525U/arcgis/rest/services/NJTransit_Rail_Linea/FeatureServer/10/query?outFields=*&where=1%3D1&f=geojson') %>%
    st_transform(crs) %>%
    mutate(line = 'No Jersey Coast') %>%
    dplyr::select(line),
  st_read('https://services6.arcgis.com/M0t0HPE53pFK525U/arcgis/rest/services/NJTransit_Rail_Linea/FeatureServer/12/query?outFields=*&where=1%3D1&f=geojson') %>%
    st_transform(crs) %>%
    mutate(line = 'Pascack Valley') %>%
    dplyr::select(line),
  st_read('https://services6.arcgis.com/M0t0HPE53pFK525U/arcgis/rest/services/NJTransit_Rail_Linea/FeatureServer/11/query?outFields=*&where=1%3D1&f=geojson') %>%
    st_transform(crs) %>%
    mutate(line = 'Raritan Valley') %>%
    dplyr::select(line)
)

st_crs(byLine)

byLine0 = 
  finalComparison %>%
  st_drop_geometry %>%
  group_by(line) %>%
  summarize(MAE2h = mean(absErrLong, na.rm = T),
            MAE30m = mean(absErrShort, na.rm = T))
# %>%
#   left_join(lines, by = 'line') %>%
#   gather(model, MAE, -line, -geometry) %>%
#   st_sf() %>%
#   mutate(model = recode(model, 
#                         'MAE2h' = '2 hours prior',
#                         'MAE30m' = '30 minutes prior'))

byLine = lines %>%
  left_join(byLine0, by = 'line')

byLine1 = byLine %>%
  dplyr::select(line, MAE2h) %>%
  rename(MAE = MAE2h) %>%
  mutate(model = '2 hours ahead')

byLine2 = byLine %>%
  dplyr::select(line, MAE30m) %>%
  rename(MAE = MAE30m) %>%
  mutate(model = '30 minutes ahead')

byLineB = rbind(byLine1, byLine2)

byLineB %>%
  ggplot() +
  geom_sf(data = st_union(njCounties),
          color='black', size=1.5, fill = NA)+
  geom_sf(data = njCounties,
          color= 'black', size=0.5,linetype = 'dashed', fill = NA) +
  geom_sf(aes(color = MAE), size = 2) +
  scale_color_gradient(high = brightRed, low = darkBlue, name = '') +
  facet_wrap(~model) +
  presentTheme()
```

```{r MAE by tile, fig.height = 9, fig.width = 8}
finalComparison = finalComparison %>%
  mutate(tile = case_when(obs < 20 ~ "<20 min",
                          obs < 40 ~ "20~40 min",
                          obs < 60 ~ "40~60 min",
                          obs < 80 ~ "60~80 min",
                          obs <= 100 ~ "80~100 min",
                          TRUE ~ ">100 min") %>%
           factor(, levels = c("<20 min", "20~40 min",
                               "40~60 min", "60~80 min",
                               "80~100 min", ">100 min")))

finalComparison1 = finalComparison1 %>%
  mutate(tile = case_when(obs < 20 ~ "<20 min",
                          obs < 40 ~ "20~40 min",
                          obs < 60 ~ "40~60 min",
                          obs < 80 ~ "60~80 min",
                          obs <= 100 ~ "80~100 min",
                          TRUE ~ ">100 min") %>%
           factor(, levels = c("<20 min", "20~40 min",
                               "40~60 min", "60~80 min",
                               "80~100 min", ">100 min")))

byTile = 
  finalComparison %>%
  group_by(tile) %>%
  summarize(meanObs = mean(obs, na.rm = T),
            meanPredLong = mean(predLong, na.rm = T),
            meanPredShort = mean(predShort, na.rm = T)) %>%
  st_drop_geometry() %>%
  gather(model, meanPred, -meanObs, -tile)%>%
  mutate(model = recode(model, 
                        'meanPredLong' = '2 hours ahead',
                        'meanPredShort' = '30 minutes ahead')) %>%
  gather(variable, value, -tile, -model) %>%
  mutate(variable = recode(variable,
                        "meanObs" = "Observed",
                        "meanPred" = "Predicted"))

byTile1 = 
  finalComparison1 %>%
  group_by(tile) %>%
  st_drop_geometry() %>%
  summarize(meanObs = mean(obs, na.rm = T),
            meanPred = mean(pred, na.rm = T)) %>%
  gather(variable, value, -tile) %>%
  mutate(variable = recode(variable,
                        "meanObs" = "Observed",
                        "meanPred" = "Predicted"))


presentPlotTheme <- function(base_size = 30, title_size = 45) {
  theme(
    text = element_text(family = 'font', color = "black"),
    plot.title = element_text(hjust = 0.5, size = title_size, colour = "black",face = "bold"), 
    plot.subtitle = element_text(hjust = 0.5,size=base_size,face="italic"),
    plot.caption = element_text(size=base_size,hjust=0),
    axis.ticks = element_blank(),
    panel.spacing = unit(3, 'lines'),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=.5),
    strip.background = element_rect(fill = "grey95", color = "black"),
    strip.text = element_text(size=base_size),
    axis.title = element_text(face = "bold",size=base_size),
    axis.text = element_text(family = 'font', size=20),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(size=base_size,colour = "black", face = "italic"),
    legend.text = element_text(size=20,colour = "black", face = "italic"),
    strip.text.x = element_text(size = base_size,face = "bold"),
    legend.key.size = unit(2, 'line')
  )
}

byTile %>%
  ggplot(aes(tile, value, shape = variable)) +
  geom_point(size = 4) +
  geom_path(aes(group = tile), color = 'black') +
  scale_shape_manual(values = c(2, 17), name = "") +
  facet_wrap(~model) +
  labs(x = 'Actual mean delay', y = 'Predicted mean delay') +
  presentPlotTheme() +
  theme(axis.text.x = element_text(angle = 90, size = 20, vjust = 0.5, hjust = 1))

byTile1 %>%
  ggplot(aes(tile, value, shape = variable)) +
  geom_point(size = 4) +
  geom_path(aes(group = tile), color = 'black') +
  scale_shape_manual(values = c(2, 17), name = "") +
  labs(x = 'Actual mean delay', y = 'Predicted mean delay') +
  presentPlotTheme() +
  theme(axis.text.x = element_text(angle = 90, size = 20, vjust = 0.5, hjust = 1))
```
